const ALERT: string = "ALERT";
const REFREST_CHAT: string = "REFREST_CHAT";
const NEW_MESSAGE_ALERT: string = "NEW_MESSAGE";
const NEW_ATTACHMENT:string = "NEW_ATTACHMENT";
const NEW_MESSAGE:string = "NEW_MESSAGE";
const MESSAGE:string = "MESSAGE";



export default { ALERT, REFREST_CHAT, NEW_MESSAGE_ALERT, NEW_ATTACHMENT, NEW_MESSAGE, MESSAGE };
